strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    it-min:
      imageName: 'ubuntu-latest'
      sq_version: LATEST_RELEASE[8.9]
    it-latest:
      imageName: 'ubuntu-latest'
      sq_version: LATEST
    it-dev:
      imageName: 'ubuntu-latest'
      sq_version: DEV
    windows:
      imageName: 'windows-latest'

pool:
  vmImage: $(imageName)

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.cache/.gradle
  SONAR_USER_HOME: $(Pipeline.Workspace)/.cache/.sonar
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - checkout: self
    submodules: recursive

  - task: Cache@2
    inputs:
      key: 'gradle | "$(Agent.OS)" | "${sq_version}" | azure-pipelines.yaml, **/build.gradle.kts, !its/sources/**'
      path: $(Pipeline.Workspace)/.cache

  - task: DownloadSecureFile@1
    condition: and(succeeded(), eq(variables.isMain, 'true'))
    name: gpgKey
    inputs:
      secureFile: 'secring.gpg'

  - task: Gradle@2
    displayName: Build ZPA
    inputs:
      tasks: 'build publishToMavenLocal'
      options: '--build-cache'

  - task: Gradle@2
    displayName: Build example of custom plugin
    condition: and(succeeded(), startsWith(variables['System.JobName'], 'it-'))
    inputs:
      tasks: 'build -p plsql-custom-rules'

  - task: Gradle@2
    displayName: Run integration tests
    condition: and(succeeded(), startsWith(variables['System.JobName'], 'it-'))
    inputs:
      tasks: 'test -Pit -Dsonar.runtimeVersion=$(sq_version) --info'
      options: '--build-cache'

  - task: SonarQubePrepare@4
    displayName: Prepare SonarQube analysis
    condition: and(succeeded(), eq(variables.isMain, 'true'), eq(variables['System.JobName'], 'linux'))
    inputs:
      SonarQube: 'SonarQube'
      scannerMode: 'Other'

  - task: Gradle@2
    displayName: Run SonarQube analysis
    condition: and(succeeded(), eq(variables.isMain, 'true'), eq(variables['System.JobName'], 'linux'))
    inputs:
      tasks: 'build'
      options: '--build-cache -Dsonar.branch.name='
      sonarQubeRunAnalysis: true

  - task: Gradle@2
    displayName: Publish artifacts
    condition: and(succeeded(), eq(variables.isMain, 'true'), eq(variables['System.JobName'], 'linux'))
    inputs:
      tasks: 'publish'
      options: '--build-cache -Psigning.secretKeyRingFile=$(gpgKey.secureFilePath) -Psigning.keyId=$(GPG_KEY_ID) -Psigning.password=$(GPG_KEY_PASSWORD)'
    env:
      DEPLOY_TOKEN: $(DEPLOY_TOKEN)
      DEPLOY_USERNAME: $(DEPLOY_USERNAME)
      OSSRH_USERNAME: $(OSSRH_USERNAME)
      OSSRH_PASSWORD: $(OSSRH_PASSWORD)

  - script: |
      # stop the Gradle daemon to ensure no files are left open (impacting the save cache operation later)
      ./gradlew --stop
