[versions]
kotlin = "2.0.20"
dokka = "1.9.20"
download = "5.6.0"
jreleaser = "1.14.0"
license = "0.16.1"
shadow = "8.3.2"
sonarscanner = "5.1.0.4882"

# libs
flatlaf = "3.5.1"
flr = "1.5.0"
jackson = "2.17.2"
jsoup = "1.18.1"
min-sonarqube = "9.9.0.65466"
min-sonarqubeapi = "9.14.0.375"
woodstox = "7.0.0"

# testing
assertj = "3.26.3"
junit = "5.11.1"
mockito = "5.13.0"
mockito-kotlin = "5.4.0"
sonarqube-orchestrator = "5.0.0.2065"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
flr-core = { module = "com.felipebz.flr:flr-core", version.ref = "flr" }
flr-testing-harness = { module = "com.felipebz.flr:flr-testing-harness", version.ref = "flr" }
flr-toolkit = { module = "com.felipebz.flr:flr-toolkit", version.ref = "flr" }
flr-xpath = { module = "com.felipebz.flr:flr-xpath", version.ref = "flr" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox" }
sonar-plugin-api = { module = "org.sonarsource.api.plugin:sonar-plugin-api", version.ref = "min-sonarqubeapi" }
sonar-plugin-api-impl = { module = "org.sonarsource.sonarqube:sonar-plugin-api-impl", version.ref = "min-sonarqube" }
sonar-ws = { module = "org.sonarsource.sonarqube:sonar-ws", version.ref = "min-sonarqube" }
sonar-orchestrator = { module = "org.sonarsource.orchestrator:sonar-orchestrator-junit5", version.ref = "sonarqube-orchestrator" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
download = { id = "de.undercouch.download", version.ref = "download" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
license = { id = "com.github.hierynomus.license", version.ref = "license" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarscanner" }
