[versions]
kotlin = "2.3.0"
dokka = "2.1.0"
download = "5.6.0"
jreleaser = "1.22.0"
license = "0.16.1"
shadow = "9.3.0"
sonarscanner = "7.2.2.6593"

# libs
flatlaf = "3.7"
flr = "1.5.0"
jackson = "2.20.1"
jsoup = "1.22.1"
min-sonarqube = "25.8.0.111929"
min-sonarqubeapi = "13.0.0.3026"
woodstox = "7.1.1"

# testing
assertj = "3.27.6"
junit = "6.0.1"
mockito = "5.21.0"
mockito-kotlin = "6.1.0"
sonarqube-orchestrator = "6.0.3.3907"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
flr-core = { module = "com.felipebz.flr:flr-core", version.ref = "flr" }
flr-testing-harness = { module = "com.felipebz.flr:flr-testing-harness", version.ref = "flr" }
flr-toolkit = { module = "com.felipebz.flr:flr-toolkit", version.ref = "flr" }
flr-xpath = { module = "com.felipebz.flr:flr-xpath", version.ref = "flr" }
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-xml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-xml", version.ref = "jackson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
woodstox = { module = "com.fasterxml.woodstox:woodstox-core", version.ref = "woodstox" }
sonar-plugin-api = { module = "org.sonarsource.api.plugin:sonar-plugin-api", version.ref = "min-sonarqubeapi" }
sonar-plugin-api-impl = { module = "org.sonarsource.sonarqube:sonar-plugin-api-impl", version.ref = "min-sonarqube" }
sonar-ws = { module = "org.sonarsource.sonarqube:sonar-ws", version.ref = "min-sonarqube" }
sonar-orchestrator = { module = "org.sonarsource.orchestrator:sonar-orchestrator-junit5", version.ref = "sonarqube-orchestrator" }
dokka-javadoc-plugin = { module = "org.jetbrains.dokka-javadoc:org.jetbrains.dokka-javadoc.gradle.plugin", version.ref = "dokka" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
license-gradle-plugin = { module = "com.github.hierynomus.license:com.github.hierynomus.license.gradle.plugin", version.ref = "license" }
jreleaser-gradle-plugin = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version.ref = "jreleaser" }
sonarqube-gradle-plugin = { module = "org.sonarqube:org.sonarqube.gradle.plugin", version.ref = "sonarscanner" }

[plugins]
download = { id = "de.undercouch.download", version.ref = "download" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
